sudo: required

services:
  - docker

language: php

php:
  - 7.2

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - docker-compose up -d

before_script:
  - composer install --prefer-dist --no-interaction

script:
  - vendor/bin/phpunit --coverage-clover build/logs/clover.xml
  - php artisan dusk

after_success:
  - bash <(curl -s https://codecov.io/bash)
