version: '2'
services:
  opencycle:
    image: opencycle/opencycle
    volumes:
      - app:/var/www/html
  nginx:
    image: opencycle/nginx
    volumes:
      - app:/var/www/html
    ports:
      - "80:80"
volumes:
  app:
